name: Cypress Tests

on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [cypress.trigger.dev]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          record: true
          env: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_AMAR_BASE_URL: ${{ secrets.AMAR_BASE_URL }}
          CYPRESS_BASE_URL: ${{ secrets.AMAR_BASE_URL }}